apiVersion: v2
name: k8s-jupyterhub-r2d
description: A Helm chart for JupyterHub with Traefik ingress
version: 0.1.0
appVersion: 1.0
dependencies:
  - name: jupyterhub
    version: "1.2.0"
    repository: "https://jupyterhub.github.io/helm-chart/"
