proxy:
  secretToken: "d9bf2609abbaba0d90a9bed1896954a3cb50d2f4e4df4d9f268b5970ba51e623"
  service:
    type: ClusterIP

hub:
  cookieSecret: "8c12bccba43ad0469f7a44bf7c6b4952cd7bd8931ae4352311d3c217bce1cc8d"

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: ""
      paths: ["/"]
  tls:
    enabled: false
    secretName: "jupyterhub-tls"

traefik:
  enabled: true
  dashboard:
    enabled: true
    domain: ""
  ssl:
    enabled: false
    domains: []
