proxy:
  secretToken: "8c1206c39fdfe3bf1044f3e7ba82b3bcdc91ea7571e3d44ed48961c8bcf82732"
  service:
    type: ClusterIP

hub:
  cookieSecret: "39518658e817ddd4d4e4be27914db6f5d45c41b8e37315a0287fbf7c54cecb4d"
  extraEnv:
    DUMMY_AUTH_PASSWORD: "default_password"

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: ""
      paths: ["/"]
  tls:
    enabled: false
    secretName: "jupyterhub-tls"

traefik:
  enabled: true
  dashboard:
    enabled: true
    domain: ""
  ssl:
    enabled: false
    domains: []
